---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freenas-test-pvc
spec:
  storageClassName: truenas-nfs-csi-api
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi